apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deploy
  labels:
    app: calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: altonliew11/calc:latest
        ports:
        - containerPort: 3001